#!/usr/bin/env node

/**
 *
 * @author xgqfrms
 * @license MIT
 * @copyright xgqfrms 2021.10.14
 *
 * @description PORT_ENV Genarator
 * @augments
 * @example node env-generator.js env=dev
 *
 */

 const shell = require("shelljs");

const fs = require("fs");

const {
  version,
  argv,
  platform,
  // versions,
  // arch,
  // env,
} = process;

// check windows or mac ???
// console.log('process.arch =', process.arch);
// console.log('process.platform =', process.platform === 'darwin' ? 'macOS' : 'Windows');
// arch: 'x64',
// platform: 'darwin',

const packageInfo = require("./package.json");

// v12.18.0
console.log('\n🚀 your node.js version =', version.substr(1).split('.')[0]);

console.log('\n your platform =', platform === 'darwin' ? 'macOS' : 'Windows');

const isMac = (platform === 'darwin');

const args = argv.slice(2) || [];

const isPureNumber = (str = '') => {
  const numberDict = [...''.padEnd(10, 'x')].map((item, i) => `${i}`);
  const arr = `${str}`.split('');
  return arr.every(item => numberDict.includes(item));
}

let key = "";
let env = "";
if (!args[0]) {
  args[0] = "";
  console.log(`ape version = ${packageInfo.version}`);
  key = 'PORT_ENV';
  env = 8080;
} else {
  const tempArr = args[0].split('=');
  key = tempArr[0] || 'PORT_ENV';
  env = isPureNumber(tempArr[1]) ? parseInt(tempArr[1]) : tempArr[1];
}

let command = ``;

// old version
if (isPureNumber(env)) {
  // npm / yarn
  // command = `./node_modules/cross-env/dist/bin/cross-env.js ${key}=${env} && yarn dev`;
  // command = `./node_modules/cross-env/dist/bin/cross-env.js ${key}=${env} && npm run dev`;
  // command = `./node_modules/cross-env/dist/bin/cross-env.js ${key}=${env}`;
  if(isMac) {
    command = `export ${key}=${env}`;
  } else {
    command = `set ${key}=${env}`;
  }
} else {
  command = `./node_modules/cross-env/dist/bin/cross-env.js ${key}='${env}' && yarn dev`;
}

// new version
// if (isPureNumber(env)) {
//   // npm / yarn
//   command = `./node_modules/cross-env/src/bin/cross-env.js ${key}=${env} && yarn dev`;
// } else {
//   command = `./node_modules/cross-env/src/bin/cross-env.js ${key}='${env}' && yarn dev`;
// }

// PORT_ENV=8090
// shelljs 执行 command

// shell.exec("\necho node.js version: && node -v");


shell.exec(command);

console.log('\n command =', command);
console.log('\n PORT_ENV =', process.env.PORT_ENV);


console.log('\n🎉 finished!');
